/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpContext,
} from '@angular/common/http';
import { Observable } from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { CollectionResponsePaymentPlanRead } from '../model/collectionResponsePaymentPlanRead';
// @ts-ignore
import { CreatePaymentPlanRequest } from '../model/createPaymentPlanRequest';
// @ts-ignore
import { ErrorResponse } from '../model/errorResponse';
// @ts-ignore
import { PaymentPlanRead } from '../model/paymentPlanRead';
// @ts-ignore
import { UpdatePaymentPlanRequest } from '../model/updatePaymentPlanRequest';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';

@Injectable({
  providedIn: 'root',
})
export class PaymentPlansService extends BaseService {
  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string | string[],
    @Optional() configuration?: Configuration,
  ) {
    super(basePath, configuration);
  }

  /**
   * Create Payment Plan
   * @endpoint post /api/v1/accounts/{account_id}/payment-plans/
   * @param accountId
   * @param createPaymentPlanRequest
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public createPaymentPlanApiV1AccountsAccountIdPaymentPlansPost(
    accountId: string,
    createPaymentPlanRequest: CreatePaymentPlanRequest,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<PaymentPlanRead>;
  public createPaymentPlanApiV1AccountsAccountIdPaymentPlansPost(
    accountId: string,
    createPaymentPlanRequest: CreatePaymentPlanRequest,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpResponse<PaymentPlanRead>>;
  public createPaymentPlanApiV1AccountsAccountIdPaymentPlansPost(
    accountId: string,
    createPaymentPlanRequest: CreatePaymentPlanRequest,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpEvent<PaymentPlanRead>>;
  public createPaymentPlanApiV1AccountsAccountIdPaymentPlansPost(
    accountId: string,
    createPaymentPlanRequest: CreatePaymentPlanRequest,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<any> {
    if (accountId === null || accountId === undefined) {
      throw new Error(
        'Required parameter accountId was null or undefined when calling createPaymentPlanApiV1AccountsAccountIdPaymentPlansPost.',
      );
    }
    if (createPaymentPlanRequest === null || createPaymentPlanRequest === undefined) {
      throw new Error(
        'Required parameter createPaymentPlanRequest was null or undefined when calling createPaymentPlanApiV1AccountsAccountIdPaymentPlansPost.',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (AccessTokenCookie) required

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json']);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined =
      this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/v1/accounts/${this.configuration.encodeParam({ name: 'accountId', value: accountId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: 'uuid' })}/payment-plans/`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<PaymentPlanRead>('post', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: createPaymentPlanRequest,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
      reportProgress: reportProgress,
    });
  }

  /**
   * Get Payment Plan
   * @endpoint get /api/v1/accounts/{account_id}/payment-plans/{payment_plan_id}
   * @param accountId
   * @param paymentPlanId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getPaymentPlanApiV1AccountsAccountIdPaymentPlansPaymentPlanIdGet(
    accountId: string,
    paymentPlanId: string,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<PaymentPlanRead>;
  public getPaymentPlanApiV1AccountsAccountIdPaymentPlansPaymentPlanIdGet(
    accountId: string,
    paymentPlanId: string,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpResponse<PaymentPlanRead>>;
  public getPaymentPlanApiV1AccountsAccountIdPaymentPlansPaymentPlanIdGet(
    accountId: string,
    paymentPlanId: string,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpEvent<PaymentPlanRead>>;
  public getPaymentPlanApiV1AccountsAccountIdPaymentPlansPaymentPlanIdGet(
    accountId: string,
    paymentPlanId: string,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<any> {
    if (accountId === null || accountId === undefined) {
      throw new Error(
        'Required parameter accountId was null or undefined when calling getPaymentPlanApiV1AccountsAccountIdPaymentPlansPaymentPlanIdGet.',
      );
    }
    if (paymentPlanId === null || paymentPlanId === undefined) {
      throw new Error(
        'Required parameter paymentPlanId was null or undefined when calling getPaymentPlanApiV1AccountsAccountIdPaymentPlansPaymentPlanIdGet.',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (AccessTokenCookie) required

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json']);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/v1/accounts/${this.configuration.encodeParam({ name: 'accountId', value: accountId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: 'uuid' })}/payment-plans/${this.configuration.encodeParam({ name: 'paymentPlanId', value: paymentPlanId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: 'uuid' })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<PaymentPlanRead>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
      reportProgress: reportProgress,
    });
  }

  /**
   * Get Payment Plans
   * @endpoint get /api/v1/accounts/{account_id}/payment-plans/
   * @param accountId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getPaymentPlansApiV1AccountsAccountIdPaymentPlansGet(
    accountId: string,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<CollectionResponsePaymentPlanRead>;
  public getPaymentPlansApiV1AccountsAccountIdPaymentPlansGet(
    accountId: string,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpResponse<CollectionResponsePaymentPlanRead>>;
  public getPaymentPlansApiV1AccountsAccountIdPaymentPlansGet(
    accountId: string,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpEvent<CollectionResponsePaymentPlanRead>>;
  public getPaymentPlansApiV1AccountsAccountIdPaymentPlansGet(
    accountId: string,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<any> {
    if (accountId === null || accountId === undefined) {
      throw new Error(
        'Required parameter accountId was null or undefined when calling getPaymentPlansApiV1AccountsAccountIdPaymentPlansGet.',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (AccessTokenCookie) required

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json']);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/v1/accounts/${this.configuration.encodeParam({ name: 'accountId', value: accountId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: 'uuid' })}/payment-plans/`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<CollectionResponsePaymentPlanRead>(
      'get',
      `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? { withCredentials } : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * Update Payment Plan
   * @endpoint patch /api/v1/accounts/{account_id}/payment-plans/{payment_plan_id}
   * @param accountId
   * @param paymentPlanId
   * @param updatePaymentPlanRequest
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public updatePaymentPlanApiV1AccountsAccountIdPaymentPlansPaymentPlanIdPatch(
    accountId: string,
    paymentPlanId: string,
    updatePaymentPlanRequest: UpdatePaymentPlanRequest,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<PaymentPlanRead>;
  public updatePaymentPlanApiV1AccountsAccountIdPaymentPlansPaymentPlanIdPatch(
    accountId: string,
    paymentPlanId: string,
    updatePaymentPlanRequest: UpdatePaymentPlanRequest,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpResponse<PaymentPlanRead>>;
  public updatePaymentPlanApiV1AccountsAccountIdPaymentPlansPaymentPlanIdPatch(
    accountId: string,
    paymentPlanId: string,
    updatePaymentPlanRequest: UpdatePaymentPlanRequest,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpEvent<PaymentPlanRead>>;
  public updatePaymentPlanApiV1AccountsAccountIdPaymentPlansPaymentPlanIdPatch(
    accountId: string,
    paymentPlanId: string,
    updatePaymentPlanRequest: UpdatePaymentPlanRequest,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<any> {
    if (accountId === null || accountId === undefined) {
      throw new Error(
        'Required parameter accountId was null or undefined when calling updatePaymentPlanApiV1AccountsAccountIdPaymentPlansPaymentPlanIdPatch.',
      );
    }
    if (paymentPlanId === null || paymentPlanId === undefined) {
      throw new Error(
        'Required parameter paymentPlanId was null or undefined when calling updatePaymentPlanApiV1AccountsAccountIdPaymentPlansPaymentPlanIdPatch.',
      );
    }
    if (updatePaymentPlanRequest === null || updatePaymentPlanRequest === undefined) {
      throw new Error(
        'Required parameter updatePaymentPlanRequest was null or undefined when calling updatePaymentPlanApiV1AccountsAccountIdPaymentPlansPaymentPlanIdPatch.',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (AccessTokenCookie) required

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json']);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined =
      this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/v1/accounts/${this.configuration.encodeParam({ name: 'accountId', value: accountId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: 'uuid' })}/payment-plans/${this.configuration.encodeParam({ name: 'paymentPlanId', value: paymentPlanId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: 'uuid' })}`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<PaymentPlanRead>('patch', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      body: updatePaymentPlanRequest,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
      reportProgress: reportProgress,
    });
  }
}
