/**
 * FinanzApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tipos de cuenta financiera aceptados.
 */
export const AccountTypeEnum = {
    Cash: 'cash',
    Bank: 'bank',
    CreditCard: 'credit_card',
    Savings: 'savings',
    Investment: 'investment',
    Other: 'other'
} as const;
export type AccountTypeEnum = typeof AccountTypeEnum[keyof typeof AccountTypeEnum];

