/**
 * FinanzApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Roles aceptados en account_group_members
 */
export const AccountGroupMemberRoleEnum = {
    Owner: 'owner',
    Admin: 'admin',
    Member: 'member'
} as const;
export type AccountGroupMemberRoleEnum = typeof AccountGroupMemberRoleEnum[keyof typeof AccountGroupMemberRoleEnum];

