/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Presupuesto vigente en un mes junto al gasto real de ese mes.
 */
export interface BudgetProgressRead {
  category_id: string;
  category_name: string;
  parent_id: string | null;
  amount: number;
  spent: number;
  remaining: number;
  percentage: number;
}
