/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Representación pública de un periodo de presupuesto.
 */
export interface BudgetRead {
  id: string;
  category_id: string;
  amount: number;
  valid_from: string;
  valid_to: string | null;
  created_by: string | null;
  updated_by: string | null;
  created_at: string;
  updated_at: string;
}
