/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Fila del desglose por categoría raíz, en céntimos.  `root_category_id`/`root_category_name` van a nulo en la fila que agrupa lo no categorizado. `expense` conserva el signo almacenado (negativo): `daily` es el único punto del dominio que devuelve magnitud (transactions.md §5).
 */
export interface CategorySummaryRead {
  root_category_id: string | null;
  root_category_name: string | null;
  income: number;
  expense: number;
  transaction_count: number;
}
