/**
 * FinanzApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountGroupMemberRoleEnum } from './accountGroupMemberRoleEnum';


/**
 * Cuerpo de PATCH /account-groups/{group_id}/members/{user_id}
 */
export interface ChangeGroupMemberRoleRequest { 
    role: AccountGroupMemberRoleEnum;
}
export namespace ChangeGroupMemberRoleRequest {
}


