/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BudgetRead } from './budgetRead';

export interface CollectionResponseBudgetRead {
  items: Array<BudgetRead>;
}
