/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvitationRead } from './invitationRead';

export interface CollectionResponseInvitationRead {
  items: Array<InvitationRead>;
}
