/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategorySummaryRead } from './categorySummaryRead';

export interface CollectionResponseCategorySummaryRead {
  items: Array<CategorySummaryRead>;
}
