/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountRead } from './accountRead';

export interface CollectionResponseAccountRead {
  items: Array<AccountRead>;
}
