/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BudgetProgressRead } from './budgetProgressRead';

export interface CollectionResponseBudgetProgressRead {
  items: Array<BudgetProgressRead>;
}
