/**
 * FinanzApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupRead } from './groupRead';


export interface CollectionResponseGroupRead { 
    items: Array<GroupRead>;
}

