/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionTypeEnum } from './transactionTypeEnum';
import { FrequencyUnitEnum } from './frequencyUnitEnum';

export interface CreatePaymentPlanRequest {
  type: TransactionTypeEnum;
  amount: number;
  category_id?: string | null;
  to_account_id?: string | null;
  description?: string | null;
  next_due_date: string;
  end_date?: string | null;
  is_recurring?: boolean;
  frequency_interval?: number | null;
  frequency_unit?: FrequencyUnitEnum | null;
}
export namespace CreatePaymentPlanRequest {}
