/**
 * FinanzApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Cuerpo de POST /categories?group_id=... — group_id viaja en la query string, no aquí, mismo motivo que en accounts (ver accounts/schemas.py).
 */
export interface CreateCategoryRequest { 
    name: string;
    parent_id?: string | null;
    color?: string | null;
    icon?: string | null;
}

