/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountTypeEnum } from './accountTypeEnum';

/**
 * Cuerpo de POST /accounts?group_id=... — group_id viaja en la query string, no aquí, porque lo necesita la dependencia de autorización antes de que el body llegue a construirse (ver accounts/dependencies.py).
 */
export interface CreateAccountRequest {
  name: string;
  type?: AccountTypeEnum | null;
  opening_balance?: number | null;
  currency?: string | null;
  color?: string | null;
  icon?: string | null;
}
export namespace CreateAccountRequest {}
