/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountGroupMemberRoleEnum } from './accountGroupMemberRoleEnum';

/**
 * Cuerpo de POST /{group_id}/invitations
 */
export interface CreateInvitationRequest {
  role: AccountGroupMemberRoleEnum;
}
export namespace CreateInvitationRequest {}
