/**
 * FinanzApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Cuerpo de POST /account-groups
 */
export interface CreateGroupRequest { 
    name: string;
    color?: string | null;
    icon?: string | null;
}

