/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Un error concreto de un campo, dentro de un error de validación.
 */
export interface ErrorDetail {
  field: string;
  message: string;
}
