/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorBody } from './errorBody';

/**
 * Forma ÚNICA de todas las respuestas de error de la API.  Cualquier fallo —validación, autorización, recurso inexistente o error interno— sale con esta estructura, para que el cliente pueda escribir un solo manejador.
 */
export interface ErrorResponse {
  error: ErrorBody;
}
