/**
 * FinanzApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const FrequencyUnitEnum = {
    Day: 'day',
    Week: 'week',
    Month: 'month',
    Year: 'year'
} as const;
export type FrequencyUnitEnum = typeof FrequencyUnitEnum[keyof typeof FrequencyUnitEnum];

