/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PendingFixedExpenseRead } from './pendingFixedExpenseRead';
import { ProjectionPointRead } from './projectionPointRead';
import { PaydayRead } from './paydayRead';

/**
 * Resumen del grupo (account_groups.md §4). Los cuatro campos que dependen del ancla de cobro son null cuando el grupo no tiene ninguna.
 */
export interface GroupOverviewRead {
  net_worth: number;
  available: number;
  account_count: number;
  spent_today: number;
  transaction_count_today: number;
  payday: PaydayRead | null;
  pending_fixed_expenses: Array<PendingFixedExpenseRead>;
  pending_fixed_expenses_total: number;
  real_balance: number;
  days_remaining: number | null;
  daily_safe_spend: number | null;
  projection: Array<ProjectionPointRead> | null;
}
