/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountGroupMemberRoleEnum } from './accountGroupMemberRoleEnum';

/**
 * Representación pública de un miembro grupo en las respuestas de la API.
 */
export interface GroupMemberRead {
  id: string;
  name: string;
  email: string;
  user_id: string;
  role: AccountGroupMemberRoleEnum;
  created_at: string;
  updated_at: string;
}
export namespace GroupMemberRead {}
