/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Saldo agregado de un grupo, en céntimos. Un grupo sin cuentas activas devuelve ceros y la divisa por defecto, nunca null (accounts.md §7).
 */
export interface GroupBalanceRead {
  net_worth: number;
  available: number;
  account_count: number;
  spendable_account_count: number;
  currency: string;
}
