/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvitationStatusEnum } from './invitationStatusEnum';
import { AccountGroupMemberRoleEnum } from './accountGroupMemberRoleEnum';
import { GroupRead } from './groupRead';
import { InvitedByRead } from './invitedByRead';

/**
 * Invitación consultada por su código. Es la única que embebe el grupo: quien la consulta todavía no pertenece a él y no puede pedirlo aparte (account_groups.md §4).
 */
export interface InvitationDetailRead {
  id: string;
  group_id: string;
  invited_by: InvitedByRead | null;
  role: AccountGroupMemberRoleEnum;
  code: string;
  status: InvitationStatusEnum;
  accepted_by: string | null;
  accepted_at: string | null;
  expires_at: string;
  created_at: string;
  group: GroupRead;
}
export namespace InvitationDetailRead {}
