/**
 * FinanzApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvitationStatusEnum } from './invitationStatusEnum';
import { AccountGroupMemberRoleEnum } from './accountGroupMemberRoleEnum';
import { InvitedByRead } from './invitedByRead';


/**
 * Representación pública de una invitación a un grupo
 */
export interface InvitationRead { 
    id: string;
    group_id: string;
    invited_by: InvitedByRead | null;
    role: AccountGroupMemberRoleEnum;
    code: string;
    status: InvitationStatusEnum;
    accepted_by: string | null;
    accepted_at: string | null;
    expires_at: string;
    created_at: string;
}
export namespace InvitationRead {
}


