/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Cuerpo de POST /auth/login.
 */
export interface LoginRequest {
  email: string;
  password: string;
}
