/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionRead } from './transactionRead';

export interface PaginatedResponseTransactionRead {
  items: Array<TransactionRead>;
  total: number;
  limit: number;
  offset: number;
}
