/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Ancla de cobro del grupo: cuándo entra el próximo ingreso recurrente y cuánto (payment_plans.md §5).
 */
export interface PaydayRead {
  date: string;
  amount: number;
}
