/**
 * FinanzApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionTypeEnum } from './transactionTypeEnum';
import { FrequencyUnitEnum } from './frequencyUnitEnum';


export interface PaymentPlanRead { 
    id: string;
    account_id: string;
    to_account_id: string | null;
    category_id: string | null;
    type: TransactionTypeEnum;
    amount: number;
    description: string | null;
    next_due_date: string;
    end_date: string | null;
    is_recurring: boolean;
    is_active: boolean;
    frequency_interval: number | null;
    frequency_unit: FrequencyUnitEnum | null;
    created_by: string | null;
    updated_by: string | null;
    created_at: string;
    updated_at: string;
}
export namespace PaymentPlanRead {
}


