/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Gasto fijo que todavía tiene que salir antes del cobro.
 */
export interface PendingFixedExpenseRead {
  payment_plan_id: string;
  description: string | null;
  amount: number;
  due_date: string;
}
