/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Un punto de la curva de saldo previsto, en céntimos.
 */
export interface ProjectionPointRead {
  date: string;
  balance: number;
}
