/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Cuerpo de PUT /budgets/{category_id} — category_id viaja en la ruta, no aquí.
 */
export interface SetBudgetRequest {
  amount: number;
  valid_from?: string | null;
}
