/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Naturaleza de una transacción. transfer no es ni ingreso ni gasto, es un movimiento interno entre dos cuentas del mismo grupo.
 */
export const TransactionTypeEnum = {
  Income: 'income',
  Expense: 'expense',
  Transfer: 'transfer',
} as const;
export type TransactionTypeEnum = (typeof TransactionTypeEnum)[keyof typeof TransactionTypeEnum];
