/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionTypeEnum } from './transactionTypeEnum';
import { FrequencyUnitEnum } from './frequencyUnitEnum';

export interface UpdatePaymentPlanRequest {
  amount?: number | null;
  type?: TransactionTypeEnum | null;
  category_id?: string | null;
  description?: string | null;
  next_due_date?: string | null;
  end_date?: string | null;
  is_recurring?: boolean | null;
  frequency_interval?: number | null;
  frequency_unit?: FrequencyUnitEnum | null;
  is_active?: boolean | null;
}
export namespace UpdatePaymentPlanRequest {}
