/**
 * FinanzApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Cuerpo de PATCH /me
 */
export interface UpdateUserRequest { 
    name?: string | null;
    email?: string | null;
}

