/**
 * FinanzApp API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountTypeEnum } from './accountTypeEnum';

/**
 * Cuerpo de PATCH /accounts
 */
export interface UpdateAccountRequest {
  name?: string | null;
  type?: AccountTypeEnum | null;
  color?: string | null;
  icon?: string | null;
  is_active?: boolean | null;
}
export namespace UpdateAccountRequest {}
