/**
 * FinanzApp API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Representación pública de un usuario en las respuestas de la API.  No es el modelo de SQLAlchemy: un modelo ORM no es un tipo válido de Pydantic (FastAPI no puede generar su esquema para /docs), y aunque lo fuera, exponer el modelo de persistencia directamente acopla el contrato HTTP a las columnas de la tabla. Hoy User no tiene campos sensibles, pero la capa de todos modos debe estar separada desde el principio.
 */
export interface UserRead { 
    id: string;
    email: string;
    name: string;
    created_at: string;
    updated_at: string;
}

