import {
  Archive,
  ArchiveRestore,
  Armchair,
  ArrowLeft,
  ArrowRightLeft,
  Baby,
  Ban,
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  BriefcaseBusiness,
  BrushCleaning,
  Building,
  Bus,
  Calendar,
  CalendarClock,
  CalendarDays,
  Car,
  CarTaxiFront,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleDollarSign,
  CircleUser,
  Clapperboard,
  Clock,
  Coffee,
  Copy,
  CreditCard,
  Croissant,
  Droplets,
  Dumbbell,
  Ellipsis,
  FileText,
  Flame,
  Flower2,
  Fuel,
  Gamepad2,
  Gavel,
  Gift,
  GraduationCap,
  HandHeart,
  Heart,
  Hospital,
  Hotel,
  House,
  IdCard,
  Inbox,
  Landmark,
  LayoutDashboard,
  Lightbulb,
  ListPlus,
  LogOut,
  Lock,
  Mail,
  Monitor,
  Music,
  PartyPopper,
  PawPrint,
  Pencil,
  PersonStanding,
  PiggyBank,
  Pill,
  Plane,
  Plus,
  ReceiptText,
  Repeat,
  Sandwich,
  Search,
  SearchX,
  Settings,
  Shapes,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  SquareParking,
  Store,
  Ticket,
  TrainFront,
  Trash,
  TrendingUp,
  Umbrella,
  Unlink,
  User,
  UserCog,
  UserMinus,
  UserPlus,
  Users,
  Utensils,
  Volleyball,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  X,
  type LucideIconData,
} from '@lucide/icons';

// Stable data identifiers are retained; only the rendering library changes.
export const APP_ICONS: Readonly<Record<string, LucideIconData>> = {
  lock: Lock,
  home: House,
  apartment: Building,
  chair: Armchair,
  lightbulb: Lightbulb,
  invert_colors: Droplets,
  local_fire_department: Flame,
  wifi: Wifi,
  build: Wrench,
  cleaning_services: BrushCleaning,
  pets: PawPrint,
  shopping_cart: ShoppingCart,
  restaurant: Utensils,
  local_cafe: Coffee,
  local_bar: Wine,
  lunch_dining: Sandwich,
  bakery_dining: Croissant,
  directions_car: Car,
  local_gas_station: Fuel,
  directions_bus: Bus,
  train: TrainFront,
  local_taxi: CarTaxiFront,
  directions_bike: Bike,
  two_wheeler: Bike,
  local_parking: SquareParking,
  flight: Plane,
  local_hospital: Hospital,
  medication: Pill,
  fitness_center: Dumbbell,
  spa: Flower2,
  self_improvement: PersonStanding,
  movie: Clapperboard,
  music_note: Music,
  sports_esports: Gamepad2,
  menu_book: BookOpen,
  sports_soccer: Volleyball,
  celebration: PartyPopper,
  confirmation_number: Ticket,
  subscriptions: Repeat,
  hotel: Hotel,
  beach_access: Umbrella,
  shopping_bag: ShoppingBag,
  checkroom: Shirt,
  storefront: Store,
  card_giftcard: Gift,
  child_care: Baby,
  phone_iphone: Smartphone,
  computer: Monitor,
  work: BriefcaseBusiness,
  school: GraduationCap,
  business_center: Briefcase,
  badge: IdCard,
  savings: PiggyBank,
  account_balance: Landmark,
  credit_card: CreditCard,
  wallet: Wallet,
  payments: Banknote,
  receipt_long: ReceiptText,
  trending_up: TrendingUp,
  currency_exchange: ArrowRightLeft,
  paid: CircleDollarSign,
  security: Shield,
  gavel: Gavel,
  description: FileText,
  volunteer_activism: HandHeart,
  favorite: Heart,
  category: Shapes,
  more_horiz: Ellipsis,
  block: Ban,
  check: Check,
  settings: Settings,
  arrow_back: ArrowLeft,
  group_add: UserPlus,
  logout: LogOut,
  dashboard: LayoutDashboard,
  groups: Users,
  account_balance_wallet: Wallet,
  close: X,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  delete: Trash,
  edit: Pencil,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  playlist_add: ListPlus,
  content_copy: Copy,
  link_off: Unlink,
  manage_accounts: UserCog,
  person_remove: UserMinus,
  query_stats: ChartNoAxesCombined,
  swap_horiz: ArrowRightLeft,
  event_repeat: CalendarClock,
  insights: ChartNoAxesCombined,
  add: Plus,
  group: Users,
  person: User,
  inbox: Inbox,
  search: Search,
  search_off: SearchX,
  mail: Mail,
  error: CircleAlert,
  account_circle: CircleUser,
  calendar_month: CalendarDays,
  event: Calendar,
  archive: Archive,
  unarchive: ArchiveRestore,
  schedule: Clock,
  receipt: ReceiptText,
};

export function resolveAppIcon(name: string | null | undefined): LucideIconData {
  return (name && APP_ICONS[name]) || APP_ICONS['block'];
}
